services:
  - type: web
    name: live-sensor-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false

